apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  # Sensitive data shifted from ConfigMap to Secret
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop" 
  JWT_SECRET: "change-this-in-production"
  NEXTAUTH_SECRET: "change-this-in-production"
