apiVersion: batch/v1
kind: Job
metadata:
  name: easyshop-migration
  namespace: easyshop
spec:
  template:
    spec:
      restartPolicy: OnFailure
      # --- FIX: Docker Pull Secret Joda Gaya Hai ---
      imagePullSecrets:
      - name: docker-pull-secret
      # ----------------------------------------
      containers:
        - name: db-migration
          image: ankitkothalkar/easyshop-migration:1 # <--- यहाँ बदलाव किया गया है
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: easyshop-config
            - secretRef:
                name: easyshop-secrets
